server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZOne: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8899/userauth/ouath/token
      userAuthorization: http://localhost:8899/userauth/ouath/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyvalue: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
        -----END PUBLIC KEY-----
zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /api/loggedinuser/**
      stripPrefix: true
      url:  http://localhost:8899/userauth/
    ui:
      path: /**
      stripPrefix: true
      serviceId: web-portal
spring:
  aop:
    proxy-target-class: true